---
apiVersion: v1
kind: Pod
metadata:
  name: my-pod
spec:
  containers:
    - name: myfrontend
      image: nginx
      volumeMounts:
      - mountPath: "/usr/share/nginx/html"               
        name: my-mount
  volumes:
  - name: my-mount
    ephemeral:
      volumeClaimTemplate:
        metadata:
          labels:
            app: myfrontend
        spec:
          accessModes: [ "ReadWriteOnce" ]
          resources:
            requests:
              storage: 64Gi
