---
apiVersion: v1
kind: Pod
metadata:
  name: my-pod
spec:
  containers:
    - name: myfrontend
      image: nginx
      volumeMounts:
      - mountPath: "/usr/share/nginx/html"               
        name: my-mount
  volumes:
  - name: my-mount
    csi:
      driver: csi.hpe.com
      volumeAttributes:
        csi.storage.k8s.io/ephemeral: "true"
        inline-volume-secret-name: csi
        inline-volume-secret-namespace: vendor
        size: 64Gi
