---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-data-my-clone-redis-master-0
spec:
  dataSource:
    name: redis-data-my-redis-master-0
    kind: PersistentVolumeClaim
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-data-my-clone-redis-slave-0
spec:
  dataSource:
    name: redis-data-my-redis-slave-0
    kind: PersistentVolumeClaim
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-data-my-clone-redis-slave-1
spec:
  dataSource:
    name: redis-data-my-redis-slave-1
    kind: PersistentVolumeClaim
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
