---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: my-storageclass
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: csi.hpe.com
parameters:
  csi.storage.k8s.io/fstype: xfs
  csi.storage.k8s.io/controller-expand-secret-name: csi
  csi.storage.k8s.io/controller-expand-secret-namespace: vendor
  csi.storage.k8s.io/controller-publish-secret-name: csi
  csi.storage.k8s.io/controller-publish-secret-namespace: vendor
  csi.storage.k8s.io/node-publish-secret-name: csi
  csi.storage.k8s.io/node-publish-secret-namespace: vendor
  csi.storage.k8s.io/node-stage-secret-name: csi
  csi.storage.k8s.io/node-stage-secret-namespace: vendor
  csi.storage.k8s.io/provisioner-secret-name: csi
  csi.storage.k8s.io/provisioner-secret-namespace: vendor
reclaimPolicy: Retain
allowVolumeExpansion: true
volumeBindingMode: Immediate
