---
apiVersion: snapshot.storage.k8s.io/v1beta1
kind: VolumeSnapshotClass
metadata:
  name: my-volumesnapshotclass
  annotations:
    snapshot.storage.kubernetes.io/is-default-class: "true"
driver: csi.hpe.com
deletionPolicy: Delete
parameters:
  csi.storage.k8s.io/snapshotter-secret-name: csi
  csi.storage.k8s.io/snapshotter-secret-namespace: vendor
